### ISSUE TITLE
Sidebar Component

### ISSUE THREAD

**Issue by kpwags** [kpwags/wags-media-repository#45]
# Sidebar Component

## Description

I would like a sidebar component that gives me a quick way to navigate to the different pages. The subpages should be collapsable. It should show by default on desktop/tablet and collapse by default on mobile. It should be toggled by the menu button on the header.

## Tasks

- [x] Sidebar Items are Displayed
- [x] Sidebar Items can Collapse
- [x] Sidebar can be Hidden / Shown
- [x] Active Item is Highlighted

## Acceptance Criteria

- Sidebar displays by default on desktop / tablet
- Sidebar is hidden by default on mobile
- Sidebar menu items can collapse
- Sidebar links go to the correct page
- Sidebar can be hidden / shown
