### ISSUE TITLE
Video Services Page

### ISSUE THREAD

**Issue by kpwags** [kpwags/wags-media-repository#46]
# Video Services Page

## Description

- There should be a page that lists out the different video services (Netflix, Paramount+, etc.). 
- There should be a table with the different services with edit and delete actions. Edit would open a form allowing me to edit the service. Delete should delete the service. Deletion should be blocked if there are any TV shows or Movies assigned to the service.
- A popover should appear alerting me why.
- There should be an add button to have a form appear allowing me to add a new service. 

## Tasks

- [x] Build table
- [x] Add button opens the add new service form
- [x] Edit buttons open the edit service form
- [x] Delete button deletes the service
- [x] Delete button is disabled if it cannot be deleted
- [x] Popover shows on the delete button

## Acceptance Criteria

- Table displays all available services
- Add button opens the add new service form
- Edit buttons open the edit service form
- Delete button deletes the service
- Delete button is disabled if it cannot be deleted
- Popover shows on the delete button
