### ISSUE TITLE
Video Service Form

### ISSUE THREAD

**Issue by kpwags** [kpwags/wags-media-repository#47]
# Video Service Form

## Description

A form should be available to add or edit a video service. It should have the following fields, both of which are required.

- Name
- Color Code

Saving the form should update the database, close the form, and display the updated video services.

## Tasks

- [x] Build Form
- [x] Load existing service into form if it exists
- [x] Save data to database
- [x] Refresh services on completion

## Acceptance Criteria

- Form is built
- Name and color code fields are displayed and are both required
- Validation on save
- Data is sent and updated to API
- Data is pre-filled on edit
