### ISSUE TITLE
Video Genres Page

### ISSUE THREAD

**Issue by kpwags** [kpwags/wags-media-repository#63]
# Video Genres Page

## Description

- There should be a page that lists out the different video genres (Comedy, Science Fiction, etc.). 
- There should be a table with the different genres with edit and delete actions. Edit would open a form allowing me to edit the genre. Delete should delete the genre. Deletion should be blocked if there are any TV shows or Movies assigned to the genre.
- A popover should appear alerting me why.
- There should be an add button to have a form appear allowing me to add a new genre. 

## Tasks

- [ ] Build table
- [ ] Add button opens the add new genre form
- [ ] Edit buttons open the edit genre form
- [ ] Delete button deletes the genre
- [ ] Delete button is disabled if it cannot be deleted
- [ ] Popover shows on the delete button

## Acceptance Criteria

- Table displays all available genres
- Add button opens the add new genre form
- Edit buttons open the edit genre form
- Delete button deletes the genre
- Delete button is disabled if it cannot be deleted
- Popover shows on the delete button
