### ISSUE TITLE
Video Genre Form

### ISSUE THREAD

**Issue by kpwags** [kpwags/wags-media-repository#64]
# Video Genre Form

## Description

A form should be available to add or edit a video genre. It should have the following fields, both of which are required.

- Name
- Color Code

Saving the form should update the database, close the form, and display the updated video genres.

## Tasks

- [ ] Build Form
- [ ] Load existing genre into form if it exists
- [ ] Save data to database
- [ ] Refresh genres on completion

## Acceptance Criteria

- Form is built
- Name and color code fields are displayed and are both required
- Validation on save
- Data is sent and updated to API
- Data is pre-filled on edit
